export interface Client {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  addressLine1: string;
  addressLine2?: string;
  townCity: string;
  countyState: string;
  postcodeZip: string;
  country: string;
  onEmailList: boolean;
  basisForProcessing: string;
  dataProtectionDate: string;
  generalInformation?: string;
  categories: string[];
  interests: string[];
  createdAt: string;
  updatedAt: string;
}

export const CATEGORIES = [
  "Architect",
  "Art Basel Hong Kong",
  "Art Basel Miami Beach",
  "Art Basel, Basel",
  "Art Cologne",
  "Art Consultant",
  "Art Fair",
  "Art Mumbai",
  "Art Services",
  "Artist",
  "Artnet",
  "Artsy",
  "Asia",
  "Asia email List",
  "Asia Postal Mailing List",
  "Auction House",
  "cards only",
  "catalogues (and included in Postal Mailing List)",
  "Chinese Press",
  "Collector",
  "Corporate Collection",
  "Curator",
  "Dealer",
  "Design",
  "Dinners HK",
  "Dinners HK - B List",
  "Dinners London",
  "Dinners NY",
  "Dinners Palm Beach",
  "E-mailing list (London only)",
  "Enoc Perez Mailing List (DYLAN's PEOPLE)",
  "Europe",
  "Events & Marketing",
  "Finance & Investment",
  "Foundation",
  "Friend",
  "Frieze London",
  "Frieze Masters (London)",
  "HC Art Fair Preview Masterlist",
  "HK Press Masterlist",
  "Hong Kong",
  "Hotel",
  "Interior Designer",
  "Lawyer",
  "Media",
  "Museum",
  "New York",
  "Palm Beach / Florida",
  "Press",
  "Press Masterlist",
  "Property",
  "Publisher",
  "Secondary contact record",
  "Services",
  "TEFAF Maastricht",
  "TEFAF NY",
  "The Armory Show",
  "USA",
  "VIP",
  "VIP Armory",
  "VIP Art Basel",
  "VIP Art Basel Hong Kong",
  "VIP Art Basel Miami Beach",
  "VIP Art Cologne",
  "VIP FIAC",
  "VIP Frieze Masters",
  "VIP Photo London",
  "VIP TEFAF Maastricht",
  "VIP TEFAF NY",
  "VIP Westbund",
  "VIP Zona Maco",
  "West Bund",
  "Young Collectors"
];

export const INTERESTS = [
  "Photography",
  "Asian 20th Century",
  "Asian Contemporary",
  "Furniture",
  "Impressionist and Modern",
  "Italian Post War",
  "Post War and Contemporary",
  "Sculpture",
  "Video & New Media",
  "Works on Paper",
  "African Art",
  "Alberto Burri",
  "Alex Katz",
  "Alexander Calder",
  "Alighiero Boetti",
  "Alighiero Boetti - Biro",
  "Alighiero Boetti - embroidery",
  "Andy Warhol",
  "Anselm Kiefer",
  "Antoni Tàpies",
  "Awol Erizku",
  "Bernd & Hilla Becher",
  "Caio Fonseca",
  "Candida Höfer",
  "Chen Wei",
  "Claude & François-Xavier Lalanne",
  "Damien Hirst",
  "Desmond Lazaro",
  "Djamel Tatah",
  "Ena Swansea",
  "Enoc Perez",
  "Enrico Castellani",
  "François-Xavier Lalanne",
  "Frank Auerbach",
  "Gavin Turk",
  "Gerhard Richter",
  "Gert & Uwe Tobias",
  "Gilbert & George",
  "Günther Uecker",
  "Hank Willis Thomas",
  "Heinz Mack",
  "Heribert C. Ottersbach",
  "Hiroshi Sugimoto",
  "Hyon Gyon",
  "Jan Worst",
  "Jean-Michel Basquiat",
  "Jeff Koons",
  "Jiang Pengyi",
  "José Parlá",
  "Julian Charrière",
  "Keith Haring",
  "Kitty Chou",
  "Livien Yin",
  "Luca Giordano",
  "Lucio Fontana",
  "Martin Mull",
  "Matthias Schaller",
  "Miguel Angel Payano Jr.",
  "Miquel Barceló",
  "Miya Ando",
  "Nabil Nahas",
  "Nobuyoshi Araki",
  "Not Vital",
  "Ori Gersht",
  "Otto Piene",
  "Pablo Picasso",
  "Paul Anthony Smith",
  "Piero Dorazio",
  "Qin Feng",
  "Rob and Nick Carter",
  "Robert Indiana",
  "Ron Arad",
  "Roy Lichtenstein",
  "Sean Scully",
  "Sigmar Polke",
  "Simon Birch",
  "Thomas Ruff",
  "Thomas Struth",
  "Tom Wesselmann",
  "Tony Bevan",
  "Tseng Kwong Chi",
  "Vik Muniz",
  "Vivian Ho",
  "Wang Keping",
  "Willem de Kooning",
  "Yan Pei Ming",
  "Ye Linghan",
  "Yoan Capote",
  "Yunizar",
  "Yves Klein",
  "Zao Wou-Ki"
];

export const BASIS_FOR_PROCESSING_OPTIONS = [
  "Details supplied through a website form or visitors' book",
  "Business card received at an event",
  "Referral from existing client",
  "Public directory or database",
  "Social media connection",
  "Email subscription",
  "Other"
];

export const COUNTRIES = [
  "United Kingdom",
  "United States",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Canada",
  "Australia",
  "Japan",
  "China",
  "Hong Kong",
  "Singapore",
  "Other"
];
